/**
 * Smart Factory IoT
 * Smart Factory IoT
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SmsDTO { 
    numberTo?: string;
    message?: string;
}